In [ ]:
import numpy as np

In [ ]:
A = np.array([[0.0, 1.0, -3.0], [2.0, 3.0, -1.0], [4.0, 5.0, -2.0]])
B = np.array([[-5.0], [7.0], [10.0]])

In [25]:
row_index = list(range(len(A)))
print(row_index)
print(len(row_index))

[0, 1, 2]
3


In [26]:
col_index = len(A[0])
print(A[0])
print(col_index)

[ 0.  1. -3.]
3


In [ ]:
def check_matrix(a,b):
  print(a)
  print('==================')
  print(b)

In [27]:
pivot_mat = []

In [28]:
A[1][0]

2.0

In [29]:
def find_rows_with_nonzero(AA,r,row_index):
  for c in range(len(row_index)):
    if AA[c][r] != 0.0:
      rows_with_nonzero = c
      pivot_number = AA[c][r]
      break
  print(rows_with_nonzero)
  print(pivot_number)
  return rows_with_nonzero

In [ ]:
#암기하기

In [ ]:
import copy
def change(inp_list, inp1, inp2):
  tmp = copy.deepcopy(inp_list[inp1])
  inp_list[inp1] = inp_list[inp2]
  inp_list[inp2] = tmp
  result = inp_list
  return inp_list

In [33]:
pivot_row = np.zeros(col_index, dtype=int)
print(pivot_row)

[0 0 0]


In [34]:
pivot_row[0] = find_rows_with_nonzero(A,0,row_index)
print(pivot_row[0])
pivot = A[pivot_row[0]][0]
print(pivot)

1
2.0
1
2.0


In [ ]:
rows_with_nonzero = 2
a = change(A,0, rows_with_nonzero)
b = change(B,0, rows_with_nonzero)
print(a)
print(b)

[[ 4.  5. -2.]
 [ 2.  3. -1.]
 [ 0.  1. -3.]]
[[10.]
 [ 7.]
 [-5.]]


In [ ]:
rows_with_nonzero = 2
a = change(A,0, rows_with_nonzero)
b = change(B,0, rows_with_nonzero)
check_matrix(a,b)
print(a)
print(b)

[[ 0.  1. -3.]
 [ 2.  3. -1.]
 [ 4.  5. -2.]]
[[-5.]
 [ 7.]
 [10.]]
[[ 0.  1. -3.]
 [ 2.  3. -1.]
 [ 4.  5. -2.]]
[[-5.]
 [ 7.]
 [10.]]
