In [153]:
import numpy as np

In [154]:
A = np.array([[0.0, 1.0, -3.0], [2.0, 3.0, -1.0], [4.0, 5.0, -2.0]])
B = np.array([[-5.0], [7.0], [10.0]])

In [155]:
row_index = list(range(len(A)))
print(row_index)
print(len(row_index))

[0, 1, 2]
3


In [156]:
col_index = len(A[0])
print(A[0])
print(col_index)

[ 0.  1. -3.]
3


In [157]:
def check_matrix(a,b):
  print(a)
  print('==================')
  print(b)

In [158]:
pivot_mat = [ ]

In [159]:
A[1][0]

2.0

In [160]:
def find_rows_with_nonzero(AA,r,row_index):
  for c in range(r,len(row_index)):
    if AA[c][r] != 0.0:
      rows_with_nonzero = c
      pivot_number = AA[c][r]
      break
  print(rows_with_nonzero)
  print(pivot_number)
  return rows_with_nonzero

In [161]:
#암기하기

In [162]:
import copy
def change(inp_list, inp1, inp2): #열바꾸는거
  tmp = copy.deepcopy(inp_list[inp1])
  inp_list[inp1] = inp_list[inp2]
  inp_list[inp2] = tmp
  result = inp_list
  return inp_list

In [163]:
pivot_row = np.zeros(col_index, dtype=int)
print(pivot_row)

[0 0 0]


In [164]:
pivot_row[0] = find_rows_with_nonzero(A,0,row_index)
print(pivot_row[0])
pivot = A[pivot_row[0]][0]
print(pivot)

1
2.0
1
2.0


In [165]:
if pivot_row[0] != 0:
  a = change(A,0,pivot_row[0])
  b = change(B,0,pivot_row[0])

In [166]:
check_matrix(a,b)

[[ 2.  3. -1.]
 [ 0.  1. -3.]
 [ 4.  5. -2.]]
[[ 7.]
 [-5.]
 [10.]]


In [167]:
a[0] = a[0]/ pivot
b[0] = b[0]/ pivot 

In [168]:
check_matrix(a,b)

[[ 1.   1.5 -0.5]
 [ 0.   1.  -3. ]
 [ 4.   5.  -2. ]]
[[ 3.5]
 [-5. ]
 [10. ]]


In [169]:
for i in range(1, len(row_index)):
  pivot = a[i][0]
  print(pivot)
  a[i] = a[i] - a[0]* pivot
  b[i] = b[i] - b[0]* pivot
check_matrix(a,b)

0.0
4.0
[[ 1.   1.5 -0.5]
 [ 0.   1.  -3. ]
 [ 0.  -1.   0. ]]
[[ 3.5]
 [-5. ]
 [-4. ]]


In [170]:
pivot_row[1] = find_rows_with_nonzero(a,1,row_index)
print(pivot_row[1])
pivot = A[pivot_row[1]][1]
print(pivot)

1
1.0
1
1.0


In [171]:
a[1] = a[1]/ pivot
b[1] = b[1]/ pivot 
check_matrix(a,b)

[[ 1.   1.5 -0.5]
 [ 0.   1.  -3. ]
 [ 0.  -1.   0. ]]
[[ 3.5]
 [-5. ]
 [-4. ]]


In [172]:
if pivot_row[1] != 1:
  a = change(A,pivot_row[1]+1,pivot_row[1])
  b = change(B,pivot_row[1]+1,pivot_row[1])

In [173]:
for i in range(2, len(row_index)):
  pivot = a[i][1]
  a[i] = a[i] - a[1]* pivot
  b[i] = b[i] - b[1]* pivot
check_matrix(a,b)

[[ 1.   1.5 -0.5]
 [ 0.   1.  -3. ]
 [ 0.   0.  -3. ]]
[[ 3.5]
 [-5. ]
 [-9. ]]
