In [52]:
import numpy as np

In [53]:
A = np.array([[3.0, -1.0, 2.0], [1.0, 1.0, 3.0], [2.0, 2.0, -1.0]])
B = np.array([[12.0], [11.0], [2.0]])

In [54]:
row_index = list(range(len(A)))
print(row_index)
print(len(row_index))

[0, 1, 2]
3


In [55]:
col_index = len(A[0])
print(A[0])
print(col_index)

[ 3. -1.  2.]
3


In [56]:
def check_matrix(a,b):
  print(a)
  print('==================')
  print(b)

In [57]:
pivot_mat = [ ]

In [58]:
A[1][0]

1.0

In [59]:
def find_rows_with_nonzero(AA,r,row_index):
  for c in range(r,len(row_index)):
    if AA[c][r] != 0.0:
      rows_with_nonzero = c
      pivot_number = AA[c][r]
      break
  print(rows_with_nonzero)
  print(pivot_number)
  return rows_with_nonzero

In [60]:
import copy
def change(inp_list, inp1, inp2): #열바꾸는거
  tmp = copy.deepcopy(inp_list[inp1])
  inp_list[inp1] = inp_list[inp2]
  inp_list[inp2] = tmp
  result = inp_list
  return inp_list

In [61]:
pivot_row = np.zeros(col_index, dtype=int)
print(pivot_row)

[0 0 0]


In [62]:
pivot_row[0] = find_rows_with_nonzero(A,0,row_index)
print(pivot_row[0])
pivot = A[pivot_row[0]][0]
print(pivot)

0
3.0
0
3.0


In [63]:
if pivot_row[0] != 0:
  a = change(A,0, pivot_row[0])
  b = change(B,0, pivot_row[0])
else:
  a = change(A,0,0)
  b = change(B,0,0)

check_matrix(a,b)

[[ 3. -1.  2.]
 [ 1.  1.  3.]
 [ 2.  2. -1.]]
[[12.]
 [11.]
 [ 2.]]


In [64]:
a[0] = a[0]/ pivot
b[0] = b[0]/ pivot 

check_matrix(a,b)

[[ 1.         -0.33333333  0.66666667]
 [ 1.          1.          3.        ]
 [ 2.          2.         -1.        ]]
[[ 4.]
 [11.]
 [ 2.]]


In [65]:
for i in range(1, len(row_index)):
  pivot = a[i][0]
  print(pivot)
  a[i] = a[i] - a[0]* pivot
  b[i] = b[i] - b[0]* pivot
check_matrix(a,b)

1.0
2.0
[[ 1.         -0.33333333  0.66666667]
 [ 0.          1.33333333  2.33333333]
 [ 0.          2.66666667 -2.33333333]]
[[ 4.]
 [ 7.]
 [-6.]]


In [66]:
pivot_row[1] = find_rows_with_nonzero(a,1,row_index)
print(pivot_row[1])
pivot = A[pivot_row[1]][1]
print(pivot)

1
1.3333333333333333
1
1.3333333333333333


In [67]:
a[1] = a[1]/ pivot
b[1] = b[1]/ pivot 
check_matrix(a,b)

[[ 1.         -0.33333333  0.66666667]
 [ 0.          1.          1.75      ]
 [ 0.          2.66666667 -2.33333333]]
[[ 4.  ]
 [ 5.25]
 [-6.  ]]


In [68]:
if pivot_row[1] != 1:
  a = change(A,pivot_row[1]+1,pivot_row[1])
  b = change(B,pivot_row[1]+1,pivot_row[1])

In [69]:
for i in range(2, len(row_index)):
  pivot = a[i][1]
  a[i] = a[i] - a[1]* pivot
  b[i] = b[i] - b[1]* pivot
  
check_matrix(a,b)

[[ 1.         -0.33333333  0.66666667]
 [ 0.          1.          1.75      ]
 [ 0.          0.         -7.        ]]
[[  4.  ]
 [  5.25]
 [-20.  ]]
